[package]
name = "Iggy-Player"
version = "0.1.0"
authors = ["Iggy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.10.3"
gstreamer = "0.16.5"
device_query = "0.1.0"
url = "1.5.1"

